export default {
    'langs': {
        'en-US': {
            'helpers.localize_defaultlang': '[instantgram] set language: ${LANG_DEFAULT} \n For more information about available languages please check http://thinkbig-company.github.io/instantgram',

            'index@alert_onlyWorks': 'Works only on instagram.com',
            'index@profilepage_downloader_disabled': 'Sorry the ProfilePage downloader is currently disabled because instagram changed their system.\n\nMaybe in the future there will be a solution to fix the problem.',
            
            'index#program@alert_dontFound': 'Did you open any Instagram post? Like for example<br/><div style="text-align:center"><a href="https://www.instagram.com/p/CIGrv1VMBkS/" target="_blank" onMouseOver="this.style.textDecoration=\'underline\'" onMouseOut="this.style.textDecoration=\'initial\'">https://www.instagram.com/p/CIGrv1VMBkS/</a></div>',
            'index#program#blob@alert_cannotDownload': 'An error has occurred!<br/><br/>Unfortunately we could not download the video try another one.',
            'index#program#profilePageDownload@str_analyzed_from_to': 'Analyzed ${data.size} Posts.',
            'index#program#profilePageDownload@is_private_modal_title': 'Profile private',
            'index#program#profilePageDownload@is_private_modal_content': 'Sorry but this profile is private and can not be downloaded. <br>Try another profile.',
            'index#program#profilePageDownload@is_private_modal_btn': 'Close',
            'index#program#profilePageDownload@stop_collecting_modal_title': 'Download started',
            'index#program#profilePageDownload@stop_collecting_modal_content_1': 'You can stop the download by clicking the stop button. If you stop the download, all the images already captured will be downloaded.',
            'index#program#profilePageDownload@stop_collecting_modal_content_2': 'If you try to download a lot of pictures at once Instagram may block your IP or your account temporarily.',
            'index#program#profilePageDownload@stop_collecting_modal_btn': 'Stop Download',
            'index#program#profilePageDownload@collect_media_modal_title': 'Please Wait',
            'index#program#profilePageDownload@collect_media_modal_content': 'Now images/videos will being collected',
            'index#program#profilePageDownload@collect_media_modal_content_download_indicator': 'Collected ${this.resolvedContent} of ${postLinks.size} Posts.',
            'index#program#profilePageDownload@collect_media_modal_btn': 'Stop collecting and start the download',
            'index#program#profilePageDownload@collection_complete_modal_title': 'Media collection complete',
            'index#program#profilePageDownload@collection_complete_modal_content_1': 'Please wait.',
            'index#program#profilePageDownload@collection_complete_modal_content_2': 'The download will be now generated.',
            'index#program#profilePageDownload@collection_complete_modal_btn': 'Close',
            'index#program#profilePageDownload@cannot_download': 'Profile could not be downloaded.',
            'index#program#profilePageDownload@download_progress_at': 'Download progress at',
            'index#program#profilePageDownload@compression_progress_at': 'Compression progress at',
            'index#program#profilePageDownload@download_failed': 'Download failed',

            'modules.modal@isLoading': 'Trying to load',

            'modules.update@consoleWarnOutdatedInfo': '[instantgram] is outdated. Please check http://thinkbig-company.github.io/instantgram for available updates.',
            'modules.update@consoleWarnOutdatedInfoVersions': '[instantgram] Installed version: ${data.version} | New update: ${data.onlineVersion}',
            'modules.update@determineIfGetUpdateIsNecessary_contacting': '[instantgram] is looking for available updates...',
            'modules.update@determineIfGetUpdateIsNecessary_updated': '[instantgram] updated your current version.',
            'modules.update@determineIfGetUpdateIsNecessary_@update_available': 'There is a new update available',
            'modules.update@determineIfGetUpdateIsNecessary_@load_update': 'Get update'
        },
        'es-AR': {
            'helpers.localize_defaultlang': '[instantgram] establecer idioma: ${LANG_DEFAULT} \n Para más información sobre los idiomas disponibles, consulte http://thinkbig-company.github.io/instantgram',

            'index@alert_onlyWorks': 'Sólo funciona en instagram.com',
            'index@profilepage_downloader_disabled': 'Lo siento, la descarga de ProfilePage está deshabilitada actualmente porque Instagram cambió su sistema.\n\nTal vez en el futuro haya una solución para solucionar el problema.',
            
            'index#program@alert_dontFound': '¿Has abierto algún post de Instagram? Como por ejemplo<br/><div style="text-align:center"><a href="https://www.instagram.com/p/CIGrv1VMBkS/" target="_blank" onMouseOver="this.style.textDecoration=\'underline\'" onMouseOut="this.style.textDecoration=\'initial\'">https://www.instagram.com/p/CIGrv1VMBkS/</a></div>',
            'index#program#blob@alert_cannotDownload': 'Se ha producido un error.<br/><br/>Desgraciadamente no hemos podido descargar el vídeo, inténtalo con otro.',
            'index#program#profilePageDownload@str_analyzed_from_to': 'Había ${data.size} se analizaron los puestos.',
            'index#program#profilePageDownload@is_private_modal_title': 'Profile private',
            'index#program#profilePageDownload@is_private_modal_content': 'Sorry but this profile is private and can not be downloaded. <br>Try another profile.',
            'index#program#profilePageDownload@is_private_modal_btn': 'Close',
            'index#program#profilePageDownload@stop_collecting_modal_title': 'Descarga iniciada',
            'index#program#profilePageDownload@stop_collecting_modal_content_1': 'Puede detener la descarga haciendo clic en el botón "Detener la descarga". Cuando se detenga la descarga, se descargarán todas las imágenes que ya se hayan capturado.',
            'index#program#profilePageDownload@stop_collecting_modal_content_2': 'Si intentas descargar muchas imágenes a la vez, Instagram puede bloquear temporalmente tu IP o tu cuenta.',
            'index#program#profilePageDownload@stop_collecting_modal_btn': 'Detener la descarga',
            'index#program#profilePageDownload@collect_media_modal_title': 'Espere, por favor',
            'index#program#profilePageDownload@collect_media_modal_content': 'Ahora se recogen las imágenes/vídeos',
            'index#program#profilePageDownload@collect_media_modal_content_download_indicator': 'Un total de ${this.resolvedContent} de ${postLinks.size} Puestos recogidos.',
            'index#program#profilePageDownload@collect_media_modal_btn': 'Deja de coleccionar y empieza a descargar',
            'index#program#profilePageDownload@collection_complete_modal_title': 'Colección de fotos/vídeos completa',
            'index#program#profilePageDownload@collection_complete_modal_content_1': 'Por favor, espere.',
            'index#program#profilePageDownload@collection_complete_modal_content_2': 'La descarga se genera ahora.',
            'index#program#profilePageDownload@collection_complete_modal_btn': 'Cerrar',
            'index#program#profilePageDownload@cannot_download': 'No se ha podido descargar el perfil.',

            'modules.modal@isLoading': 'Intentando cargar',

            'modules.update@consoleWarnOutdatedInfo': '[instantgram] es obsoleto. Consulte en http://thinkbig-company.github.io/instantgram las actualizaciones disponibles.',
            'modules.update@consoleWarnOutdatedInfoVersions': '[instantgram] Versión instalada: ${data.version} | Nueva actualización: ${data.onlineVersion}',
            'modules.update@determineIfGetUpdateIsNecessary_contacting': '[instantgram] está buscando actualizaciones disponibles...',
            'modules.update@determineIfGetUpdateIsNecessary_updated': '[instantgram] ha actualizado su versión actual.',
            'modules.update@determineIfGetUpdateIsNecessary_@update_available': 'Hay una nueva actualización disponible',
            'modules.update@determineIfGetUpdateIsNecessary_@load_update': 'Obtener información'
        },
        'de-DE': {
            'helpers.localize_defaultlang': 'Ausgewählte Sprache: ${LANG_DEFAULT} \n Weitere Informationen zu den unterstützten Sprachen findest du auf http://thinkbig-company.github.io/instantgram',

            'index@alert_onlyWorks': 'Funktioniert nur auf instagram.com',
            'index@profilepage_downloader_disabled': 'Leider ist der ProfilePage-Downloader derzeit deaktiviert, da Instagram sein System geändert hat.\n\nVielleicht gibt es in Zukunft eine Lösung für dieses Problem.',
            
            'index#program@alert_dontFound': 'Hast du einen Instagram Post geöffnet? Zum Beispiel<br/><div style="text-align:center"><a href="https://www.instagram.com/p/CIGrv1VMBkS/" target="_blank" onMouseOver="this.style.textDecoration=\'underline\'" onMouseOut="this.style.textDecoration=\'initial\'">https://www.instagram.com/p/CIGrv1VMBkS/</a></div>',
            'index#program#blob@alert_cannotDownload': 'Es ist ein fehler aufgetreten!<br/><br/>Wir konnten das Video leider nicht Downloaden versuchen Sie ein anderes.',
            'index#program#profilePageDownload@str_analyzed_from_to': 'Es wurden ${data.size} Beiträge analysiert.',
            'index#program#profilePageDownload@is_private_modal_title': 'Profil ist Privat',
            'index#program#profilePageDownload@is_private_modal_content': 'Sorry, aber dieses Profil ist privat und kann nicht heruntergeladen werden. <br>Versuchen Sie ein anderes Profil.',
            'index#program#profilePageDownload@is_private_modal_btn': 'Schließen',
            'index#program#profilePageDownload@stop_collecting_modal_title': 'Download gestarted',
            'index#program#profilePageDownload@stop_collecting_modal_content_1': 'Sie können den Download stoppen, indem Sie auf die Schaltfläche "Download stoppen" klicken. Wenn Sie das Herunterladen anhalten, werden alle bereits aufgenommenen Bilder heruntergeladen.',
            'index#program#profilePageDownload@stop_collecting_modal_content_2': 'Wenn Sie versuchen, viele Bilder auf einmal herunterzuladen, kann Instagram Ihre IP oder Ihr Konto vorübergehend sperren.',
            'index#program#profilePageDownload@stop_collecting_modal_btn': 'Download stoppen',
            'index#program#profilePageDownload@collect_media_modal_title': 'Bitte warten',
            'index#program#profilePageDownload@collect_media_modal_content': 'Bilder/Videos werden jetzt gesammelt',
            'index#program#profilePageDownload@collect_media_modal_content_download_indicator': 'Insgesamt ${this.resolvedContent} von ${postLinks.size} Beiträgen gesammelt.',
            'index#program#profilePageDownload@collect_media_modal_btn': 'Stoppen Sie das Sammeln und starten Sie den Download',
            'index#program#profilePageDownload@collection_complete_modal_title': 'Bilder/Video-Sammlung komplett',
            'index#program#profilePageDownload@collection_complete_modal_content_1': 'Bitte warten.',
            'index#program#profilePageDownload@collection_complete_modal_content_2': 'Der Download wird nun erzeugt.',
            'index#program#profilePageDownload@collection_complete_modal_btn': 'Schließen',
            'index#program#profilePageDownload@cannot_download': 'Profil konnte nicht runtergeladen werden.',
            'index#program#profilePageDownload@download_progress_at': 'Download-Fortschritt bei',
            'index#program#profilePageDownload@compression_progress_at': 'Komprimierungs-Fortschritt bei',
            'index#program#profilePageDownload@download_failed': 'Download fehlgeschlagen',

            'modules.modal@isLoading': 'Wird versucht zu laden',

            'modules.update@consoleWarnOutdatedInfo': '[instantgram] ist veraltet. Bitte besuche die Seite http://thinkbig-company.github.io/instantgram für ein Update.',
            'modules.update@consoleWarnOutdatedInfoVersions': '[instantgram] Installierte Version: ${data.version} | Neue Version: ${data.onlineVersion}',
            'modules.update@determineIfGetUpdateIsNecessary_contacting': '[instantgram] sucht nach neuen verfügbaren Updates...',
            'modules.update@determineIfGetUpdateIsNecessary_updated': '[instantgram] wurde aktualisiert.',
            'modules.update@determineIfGetUpdateIsNecessary_@update_available': 'Es ist ein neues Update verfügbar',
            'modules.update@determineIfGetUpdateIsNecessary_@load_update': 'Update laden'
        },
        'pt-BR': {
            'helpers.localize_defaultlang': '[instantgram] idioma configurado: ${LANG_DEFAULT} \npara mais informações sobre os idiomas suportados, acesse http://thinkbig-company.github.io/instantgram',

            'index@alert_onlyWorks': '[instantgram] somente funciona no instagram.com',
            'index@profilepage_downloader_disabled': 'Lamentamos que o programa de download ProfilePage esteja atualmente desativado porque o programa mudou seu sistema.\n\nTalvez, no futuro, haja uma solução para resolver o problema.',
            
            'index#program@alert_dontFound': 'ops, você está em algum post do instagram? ex:<br/><div style="text-align:center"><a href="https://www.instagram.com/p/CIGrv1VMBkS/" target="_blank" onMouseOver="this.style.textDecoration=\'underline\'" onMouseOut="this.style.textDecoration=\'initial\'">https://www.instagram.com/p/CIGrv1VMBkS/</a></div>',
            'index#program#blob@alert_cannotDownload': 'Ocorreu um erro!<br/><br/>Não pudemos baixar o vídeo infelizmente tentar outro.',
            'index#program#profilePageDownload@str_analyzed_from_to': 'Analyzed ${data.size} Posts.',
            'index#program#profilePageDownload@is_private_modal_title': 'Profile private',
            'index#program#profilePageDownload@is_private_modal_content': 'Sorry but this profile is private and can not be downloaded. <br>Try another profile.',
            'index#program#profilePageDownload@is_private_modal_btn': 'Close',
            'index#program#profilePageDownload@stop_collecting_modal_title': 'Início do download',
            'index#program#profilePageDownload@stop_collecting_modal_content_1': 'Você pode interromper o download clicando no botão de parada. Se você interromper o download, todas as imagens já capturadas serão baixadas.',
            'index#program#profilePageDownload@stop_collecting_modal_content_2': 'Se você tentar baixar muitas imagens de uma vez, a Instagram poderá bloquear temporariamente seu IP ou sua conta.',
            'index#program#profilePageDownload@stop_collecting_modal_btn': 'Parar Download',
            'index#program#profilePageDownload@collect_media_modal_title': 'Por favor, aguarde',
            'index#program#profilePageDownload@collect_media_modal_content': 'Agora imagens/videos serão coletados',
            'index#program#profilePageDownload@collect_media_modal_content_download_indicator': 'Recolhido ${este.resolvedContent} de ${postLinks.size} Correios.',
            'index#program#profilePageDownload@collect_media_modal_btn': 'Pare de coletar e inicie o download',
            'index#program#profilePageDownload@collection_complete_modal_title': 'Coleção de mídia completa',
            'index#program#profilePageDownload@collection_complete_modal_content_1': 'Por favor, aguarde.',
            'index#program#profilePageDownload@collection_complete_modal_content_2': 'O download será agora gerado.',
            'index#program#profilePageDownload@collection_complete_modal_btn': 'Fechar',
            'index#program#profilePageDownload@cannot_download': 'O perfil não pôde ser baixado.',

            'modules.modal@isLoading': 'Tentando carregar',

            'modules.update@consoleWarnOutdatedInfo': '[instantgram] está desatualizado. Acesse http://thinkbig-company.github.io/instantgram para atualizar',
            'modules.update@consoleWarnOutdatedInfoVersions': '[instantgram] versão local: ${data.version} | nova versão: ${data.onlineVersion}',
            'modules.update@determineIfGetUpdateIsNecessary_contacting': '[instantgram] está procurando atualizações...',
            'modules.update@determineIfGetUpdateIsNecessary_updated': '[instantgram] informações locais atualizadas',
            'modules.update@determineIfGetUpdateIsNecessary_@update_available': 'Há uma nova atualização disponível',
            'modules.update@determineIfGetUpdateIsNecessary_@load_update': 'Carga de actualização'
        }
    }
};